---
title: "TopTags vs DESeqResult Classes"
author: "Hildah Njoroge"
date: "2023-07-27"
output: html_document
---
================================================================================================================================================

# Load data

```{r}
load("C:/hne_files/MSc_Bioinf/MScProject-main_C/MScProject-main_10.06.23/scripts/DEG_analysis/Gene_counts/htg_pipeline/deseq2_statistical_analysis_HTG.Rdata")
```

```{r}
ddstrial <- DESeq(dds)
results(ddstrial)

```

```{r}
res_trial <- results(ddstrial)
summary(res_trial)
table(res_trial$padj < 0.1)
table(res_trial$padj < 0.05)
res_trial.05 <- results(ddstrial, alpha=.05)
table(res_trial.05$padj < .05)
summary(res_trial.05)
```

## check if DESeq class and TopTags class store the same results

## from this, I notice that the number of genes with an adjusted Pvalue \< 0.05 and a log2FC \> 1 is different between the two

```{r}
sigRes <- subset(res$table, FDR < 0.05 & abs(logFC) > 1)
# sigRes <- subset(res$table, FDR < 0.05)
sigRes_HTG <- sigRes
knitr::kable(head(sigRes))
paste("method 1 gives -->", nrow(sigRes), "genes with padjust<0.05 & absolute(logFC)>1")

sigRes_trial <- subset(res_trial, padj  < 0.05 & abs(log2FoldChange) > 1)
# sigRes_trial <- subset(res_trial, padj  < 0.05)
knitr::kable(head(sigRes_trial))
paste("method 2 gives -->", nrow(sigRes_trial), "genes with padjust<0.05 & absolute(logFC)>1")
